# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
# ---
# include:
#   - board: seeeduino_xiao_ble
#     shield: corny_left rgbled_adapter
#   - board: seeeduino_xiao_ble
#     shield: corny_right rgbled_adapter
#---
include:
  - board: xiao_ble/nrf52840/zmk
    shield: corny_left rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: xiao_ble/nrf52840/zmk
    shield: corny_right rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: xiao_ble/nrf52840/zmk
    shield: corny_dongle rgbled_adapter
  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
